# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[profile.default]
src                 = "src"
out                 = "out"
libs                = ["lib"]

auto_detect_solc    = false
solc_version        = "0.7.6"
evm_version         = "istanbul"
optimizer           = true
optimizer_runs      = 999999


[rpc_endpoints]
bsc                 = "https://bsc-dataseed.binance.org/"
bsc_testnet         = "https://data-seed-prebsc-1-s1.binance.org:8545/"


[etherscan]
bsc                 = { key = "BSCSCAN_API_KEY", url = "https://api.bscscan.com/api" }
bsc_testnet         = { key = "BSCSCAN_API_KEY", url = "https://api-testnet.bscscan.com/api" }
