# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[profile.default]
src                 = "contracts"
out                 = "artifacts"
script              = "deploy"
test                = "test"
cache_path          = "cache_forge"

libs                = [
  "lib",
]

allow_paths     = [
    "../node_modules/",
]

# Compiler settings
solc_version        = "0.8.30"
evm_version         = "cancun"
optimizer           = true
optimizer_runs      = 200

bytecode_hash       = "none"
cbor_metadata       = false
ast                 = true


[rpc_endpoints]
bsc                 = "https://bsc-dataseed.binance.org/"
bsc_testnet         = "https://data-seed-prebsc-1-s1.binance.org:8545/"


[etherscan]
bsc                 = { key = "BSCSCAN_API_KEY", url = "https://api.bscscan.com/api" }
bsc_testnet         = { key = "BSCSCAN_API_KEY", url = "https://api-testnet.bscscan.com/api" }
